# Generated by Django 4.2.7 on 2024-02-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
