# Generated by Django 4.2.7 on 2024-02-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_schedule_class_name_alter_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
    ]
