# Generated by Django 4.2.7 on 2024-02-11 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.period_number'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
    ]
