# Generated by Django 4.2.7 on 2024-02-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_absentteacher_defaultroutine_period_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period_number',
            field=models.IntegerField(),
        ),
    ]
