# Generated by Django 4.2.7 on 2024-02-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_period_subjects_period_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
