# Generated by Django 4.2.7 on 2024-02-12 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_defaultroutine_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='period',
            name='period_number',
        ),
        migrations.AddField(
            model_name='period',
            name='period_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.period_id'),
        ),
    ]
