# Generated by Django 4.2.7 on 2024-02-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_period_id_remove_period_period_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultroutine',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
