# Generated by Django 4.2.7 on 2024-02-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_defaultroutine_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period_id',
            name='period_id',
            field=models.IntegerField(),
        ),
    ]
