# Generated by Django 4.2.7 on 2024-02-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_period_id_period_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period_id',
            name='period_id',
            field=models.CharField(max_length=100),
        ),
    ]
