# Generated by Django 4.2.7 on 2024-02-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_period_id_period_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbsentTeacher',
            new_name='AbsenceTracking',
        ),
    ]
