# Generated by Django 4.2.7 on 2024-02-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_absentteacher_absencetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
