# Generated by Django 4.2.7 on 2024-02-13 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_teacher_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultroutine',
            name='date',
        ),
        migrations.CreateModel(
            name='AdjustedPeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('assigned_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
        ),
    ]
