# Generated by Django 4.2.7 on 2024-02-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_adjustedperiods_adjustedschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='extra_class_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='extra_classes_in_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
