# Generated by Django 4.2.7 on 2024-02-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_teacher_extra_class_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='leave_taken',
            field=models.IntegerField(default=0),
        ),
    ]
